#!/bin/zsh
# https://github.com/b9swift/CI-System
# Copyright (c) 2024 BB9z, MIT License

set -euo pipefail

cd "$(dirname "$0")"
export B9_ROOT="$(pwd)"

for testFile in tests/test_*.sh; do
    echo "\n[Test] $(basename "$testFile")"
    shunit2 "$testFile"
done
