#!/bin/zsh
# https://github.com/b9swift/CI-System
# Copyright (c) 2024 BB9z, MIT License

set -euo pipefail

cd "$(dirname "$0")"
export B9_ROOT="$(pwd)"

for testFile in tests/test_*.sh; do
    echo "\n[Test] $(basename "$testFile")"
    shunit2 "$testFile"
done

. "$B9_ROOT/lib/xccommand.sh"

rm -rf build

logSection "Test project no warning"
xcCommandParametersRestAll

export XC_PROJECT="tests/samples/BuildTests.xcodeproj"
export XC_SCHEME="NoWarning"
export XC_DISABLE_CODE_SIGNING=1
export XC_DESTINATION=mac
export XC_CLEAN=1
export XC_BEAUTIFY=0
./build-ios

logSection "Test workspace has warning"
xcCommandParametersRestAll

export XC_WORKSPACE="tests/samples/Tests.xcworkspace"
export XC_SCHEME="HasWarning"
export XC_DISABLE_CODE_SIGNING=1
export XC_DESTINATION=mac
export XC_CLEAN=1
export XC_BEAUTIFY=0
./build-ios

logInfo "[Done]"
