# https://github.com/b9swift/CI-System
# Copyright (c) 2024 BB9z, MIT License

name: CI

on:
  push:
  pull_request:
  schedule:
    # Every two months
    - cron: "3 4 5 */2 *"

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install shunit2
      - name: Run tests
        run: |
          ./run_tests
