name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install shunit2
      - name: Run tests
        run: |
          ./run_tests
