# https://github.com/b9swift/CI-System
# Copyright (c) 2024 BB9z, MIT License

name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Every two months
    - cron: "3 4 5 */2 *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-12]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install shunit2
      - name: Run tests
        run: |
          ./run-tests
